### ISSUE TITLE
Update docs for classification

### ISSUE THREAD

**Issue by dmiklic** [adore-hrzz/nao-sound-classification#18]
Currently, only the docs for learning and batch classification have been updated.

Docs for getting the classifier running, both as a local and as a remote module must be updated too!

**Comment by dmiklic** [comment]
Should be fixed in c30744f04a57a6efe85c1986e1c1d4786b0edbdd however, I'm leaving the issue open until someone goes over the instructions and verifies that they are actually correct as written. @fpetric see if you can assign somebody to this at some point.

**Comment by fpetric** [comment]
@dmiklic I took a look, most of the info is there but it still needs to be revised a bit so I am inclined towards leaving this open until I find some time to update it.

**Comment by dmiklic** [comment]
Agreed, let's leave it open for now.
