### ISSUE TITLE
Upgrade to naoqi 2.1

### ISSUE THREAD

**Issue by dmiklic** [adore-hrzz/nao-sound-classification#2]
Requires updates to the build system and maybe some minor changes to code.

**Comment by dmiklic** [comment]
@stribor14 I think we can close this?

**Comment by stribor14** [comment]
@dmiklic I didn't test it on naoqi2.1, maybe @fpetric  knows more about it

**Comment by fpetric** [comment]
Not sure if I tried to build it with naoqi 2.1, I will check tonight and get back to you.

**Comment by fpetric** [comment]
Not sure we tried building this with naoqi v2.1, I suggest leaving this open.

**Comment by dmiklic** [comment]
Now (a363e24d0cf3473dfb7526eabef8c2196db59511) definitely woks with 2.1. Closing.
