### ISSUE TITLE
Crash in Learner

### ISSUE THREAD

**Issue by dmiklic** [adore-hrzz/nao-sound-classification#9]
When running learner with the attached configuration files: [SC.txt](https://github.com/adore-hrzz/nao-sound-classification/files/1007761/SC.txt), [test_data.txt](https://github.com/adore-hrzz/nao-sound-classification/files/1007764/test_data.txt), [train_data.txt](https://github.com/adore-hrzz/nao-sound-classification/files/1007765/train_data.txt)

learner crashes (after processing an number of files), with the following error message:
```
4month_18weeks_old_baby_cooing_and_babbling__nonarticulated_006.wav: [||||||||||] DONE
sto_veliki_misle_mali_govore_sta_je_kisobran__speech_031.wav: [||||||||||] DONE
OpenCV Error: Internal error (data is empty) in CvMLData::set_response_idx, file /home/damjan/devel/opencv/opencv-2.4.9/modules/ml/src/data.cpp, line 347
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/damjan/devel/opencv/opencv-2.4.9/modules/ml/src/data.cpp:347: error: (-3) data is empty in function CvMLData::set_response_idx

Aborted (core dumped)
```

This is the part of the code where things fail (as reported by gdb):
```
    CvMLData modelData;
    modelData.set_miss_ch('@');
    modelData.read_csv((par.featData).c_str());
    
    modelData.set_response_idx(0);
```

@stribor14 any ideas?

**Comment by fpetric** [comment]
@dmiklic  i don't have this issue on a clean build, do you have the latest dataset? i believe @stribor14 said that there are a few whitespaces in the names of the files in the dataset that crash the software. I had this problem with folderClassify.

**Comment by dmiklic** [comment]
I thought of that, unfortunately, it seems to be a different issue, I have the correct dataset (no whitespace in file names).

Might have something to do with my build of OpenCV, I did that in a rush and was quite careless.

**Comment by fpetric** [comment]
If you also renamed the files in the dataset folder to remove whitespaces, I think the OpenCV might be the culprit.

**Comment by fpetric** [comment]
@dmiklic @stribor14 @robotiks  can we close this as there are no more reported crashes?

**Comment by dmiklic** [comment]
If you guys cannot reproduce this, then I vote to close.

**Comment by fpetric** [comment]
I've never had it. Closing it, we can reopen if the error emerges again.
